<a href="https://colab.research.google.com/github/baerashid/learningTF/blob/master/TF1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#The default is TF 1.0, so forcing to use 2.0
#run only once when creating notebook
#!pip uninstall tensorflow

In [0]:
!pip install tensorflow==2.1.0
#Now we have to restart Runtime
#Click above

In [1]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.1.0


In [2]:
ones = tf.ones([500,500])*0.5
tf.print(ones)

[[0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 ...
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]]


In [9]:
m1 = tf.constant([[1.,2.]])
m1

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 2.]], dtype=float32)>

In [24]:
x = tf.constant([[-2,-1,0.,1,2]])
negMatrix = tf.negative(x)
print(negMatrix)

tf.Tensor([[ 2.  1. -0. -1. -2.]], shape=(1, 5), dtype=float32)


In [25]:
sigma = 1.0
mu = 0.0
(1.0 / (tf.sqrt(2.0 * np.pi) * sigma)) * (tf.exp(tf.negative(tf.pow(x - mu, 2.0) / (2.0 * tf.pow(sigma, 2.0)))))

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[0.05399097, 0.24197073, 0.3989423 , 0.24197073, 0.05399097]],
      dtype=float32)>

In [0]:
#puts function into Graph
@tf.function
def neg_op(x):
  tf.print(tf.negative(x))
  return tf.negative(x)

In [29]:
result = neg_op(x)

[[2 1 -0 -1 -2]]


In [32]:
tf.config.experimental.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU')]

In [33]:
tf.get_logger()

<Logger tensorflow (INFO)>

In [0]:
#well, looging was moved in TF 2.0 into other libs. 